"""mitmproxy addon for pi-token-saver.

Redirects OpenAI-completions-style LLM API calls to the headroom proxy running
in the same podman pod, carrying the original upstream in x-headroom-* headers
so headroom forwards the (compressed) request to the real provider. All other
traffic — including non-LLM paths on intercepted hosts — is left untouched, and
hosts outside the intercept list are tunneled without TLS termination at all
(via the allow_hosts option set from the intercept-hosts file).

The intercept-hosts file is regenerated by pi-token-saver on every launch from
pi's built-in provider list plus the user's ~/.pi/agent/models.json.
"""

import os
import re

from mitmproxy import ctx, http

HEADROOM_PORT = int(os.environ.get("HEADROOM_INTERNAL_PORT", "8787"))
HOSTS_FILE = os.environ.get(
    "INTERCEPT_HOSTS_FILE", "/home/mitmproxy/.mitmproxy/intercept-hosts.txt"
)

_DEFAULT_PORTS = {"http": 80, "https": 443}


def _read_hosts() -> set[str]:
    hosts: set[str] = set()
    try:
        with open(HOSTS_FILE, encoding="utf-8") as f:
            for line in f:
                line = line.strip().lower()
                if line and not line.startswith("#"):
                    hosts.add(line)
    except OSError:
        pass
    return hosts


class TokenSaverRewrite:
    def __init__(self) -> None:
        self.hosts: set[str] = set()

    def running(self) -> None:
        self.hosts = _read_hosts()
        if self.hosts:
            pattern = (
                "^(" + "|".join(re.escape(h) for h in sorted(self.hosts)) + r")(:\d+)?$"
            )
            ctx.options.update(allow_hosts=[pattern])
            ctx.log.info(
                f"token-saver: intercepting {len(self.hosts)} host(s); "
                f"rewriting chat-completions to headroom :{HEADROOM_PORT}"
            )
        else:
            # No hosts: never terminate TLS for anything.
            ctx.options.update(allow_hosts=["^$"])
            ctx.log.warn("token-saver: intercept-hosts file empty; passthrough only")

    def request(self, flow: http.HTTPFlow) -> None:
        host = flow.request.pretty_host.lower()
        port = flow.request.port
        scheme = flow.request.scheme
        hostport = f"{host}:{port}"
        if host not in self.hosts and hostport not in self.hosts:
            return

        path = flow.request.path
        bare_path = path.split("?", 1)[0]
        query = path[len(bare_path):]

        if not bare_path.endswith("/chat/completions"):
            return  # non-LLM endpoint (e.g. /models) — leave untouched

        origin = f"{scheme}://{host}"
        if port != _DEFAULT_PORTS.get(scheme):
            origin = f"{origin}:{port}"

        flow.request.headers["x-headroom-base-url"] = origin
        flow.request.headers["x-headroom-original-path"] = bare_path
        flow.request.scheme = "http"
        flow.request.host = "127.0.0.1"
        flow.request.port = HEADROOM_PORT
        flow.request.path = "/v1/chat/completions" + query
        flow.request.host_header = f"127.0.0.1:{HEADROOM_PORT}"

    def responseheaders(self, flow: http.HTTPFlow) -> None:
        # Stream SSE bodies through immediately — buffering would stall
        # token-by-token LLM streaming until the response completes.
        ctype = flow.response.headers.get("content-type", "")
        if "text/event-stream" in ctype:
            flow.response.stream = True

        # Force the client<->proxy connection closed after each response.
        # Clients (e.g. pi's undici pool) otherwise keep the idle keep-alive
        # socket to the proxy open for undici's keepAliveMaxTimeout (~10 min),
        # which keeps their event loop alive and stalls process exit long after
        # a one-shot run has printed its answer. Real providers close idle
        # sockets quickly; this makes the proxy behave the same way. The
        # localhost pi<->proxy hop is cheap, so losing keep-alive there is
        # negligible; headroom<->provider keep-alive is unaffected.
        flow.response.headers["connection"] = "close"
        flow.response.headers.pop("keep-alive", None)


addons = [TokenSaverRewrite()]
